import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function toTitleCase(str: string): string {
  return str.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getReportFooterText(): string {
  try {
    const userStr = localStorage.getItem('user');
    const user = userStr ? JSON.parse(userStr) : null;
    if (user?.name) {
      return `This is a report generated by ${toTitleCase(user.name)}. No signature required.`;
    }
  } catch (e) {
    console.error('Failed to parse user for report footer', e);
  }
  return 'This is a report generated by Fresh Sarura. No signature required.';
}
